version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./backend/:/app"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/src"
    command: npm run dev
