version: "3"
services:
  backend:
    image: node:20
    container_name: backend-api
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - "./backend/:/app"
  frontend:
    image: node:20
    container_name: frontend-web
    working_dir: /src
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - "./frontend/:/src"
